on:
  push:
    tags:
      # Full version
      - "[0-9]+.[0-9]+.[0-9]+"
      # Prerelease version
      - "[0-9]+.[0-9]+.[0-9]+-*"

  pull_request:
    branches:
      # Trigger on pull requests into main
      - main
    types: [ opened, synchronize ]

name: Continuous integration

jobs:
  rust_matrix:
    # Outputs the strategy matrix to be used in other jobs
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.rust.outputs.matrix }}
    steps:
      - name: Define rust matrix
        id: rust
        run: |
          echo "matrix={'rust': ['stable', '1.65.0']}" >> $GITHUB_OUTPUT
  check:
    name: Check
    runs-on: ubuntu-latest
    needs: rust_matrix
    strategy:
      matrix: ${{ fromJson(needs.rust_matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    needs: rust_matrix
    strategy:
      matrix: ${{ fromJson(needs.rust_matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    needs: rust_matrix
    strategy:
      matrix: ${{ fromJson(needs.rust_matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    needs: rust_matrix
    strategy:
      matrix: ${{ fromJson(needs.rust_matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  tarpaulin:
    name: Tarpaulin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-tarpaulin
      - uses: actions-rs/cargo@v1
        with:
          command: tarpaulin
          args: --out xml
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./cobertura.xml
          verbose: true

  msrv:
    name: Find msrv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-msrv
      - uses: actions-rs/cargo@v1
        with:
          command: msrv
          args: find

  musl:
    name: Musl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: x86_64-unknown-linux-musl
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: --example docker --target x86_64-unknown-linux-musl

  publish:
    runs-on: ubuntu-latest
    needs:
      - check
      - test
      - fmt
      - clippy
      - musl
      - tarpaulin
    steps:
      - uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
      - name: Publish to crates.io on tags
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          toolchain: stable
          command: publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.PUBLISH_SECRET }}
      - name: Dry-run publish on non-tags
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          toolchain: stable
          command: publish
          args: --dry-run
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.PUBLISH_SECRET }}
